# Workflow para construir con Gradle y subir artefactos en push a main y tags snapshot

name: Java CI with Gradle

on:
  push:
    branches:
      - main       # Cambia 'main' por tu rama principal si usas otra
    tags:
      - 'snapshot' # O el patrón de tag que uses

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4.7.0
      with:
        java-version: 21
        distribution: 'zulu'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: build/libs/
