name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build
        run: ./gradlew build

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # o usa el GITHUB_TOKEN si es suficiente
        run: |
          TAG="snapshot-${{ github.run_number }}"
          gh release create "$TAG" build/libs/*.jar \
            --title "Dev Build $TAG" \
            --notes "Automatic snapshot release" \
            --prerelease
