name: Release Snapshot

on:
  push:
    branches:
      - main  # o la rama en la que haces releases

permissions:
  contents: write  # necesario para crear/modificar tags/releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}  # usar tu PAT, no GITHUB_TOKEN

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}
          automatic_release_tag: snapshot-${{ github.run_number }}
          prerelease: true
          title: Dev Build
          files: build/libs/*.jar
