name: Release JAR

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build project
        run: ./gradlew build

      - name: Generate Tag
        id: generate_tag
        run: |
          echo "tag=snapshot-${{ github.run_number }}" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.generate_tag.outputs.tag }}
          name: Dev Build ${{ steps.generate_tag.outputs.tag }}
          files: build/libs/*.jar
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # o simplemente GITHUB_TOKEN si no necesitas uno externo
