name: Automatic Snapshot Release
on:
  push:
    branches: [ main ]

permissions:
  contents: write  # recomendado, aunque el token hace lo crítico

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Aquí podrías compilar tu mod si quieres

      - name: Create or update snapshot release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          tag: snapshot
          prerelease: true
